version: "3"
services:
    mongo:
        container_name: mongo_cont
        image: mongo:latest
        volumes:
            - mongo_data:/data/db
        ports:
            - "27017:27017"
        networks:
            backend:

networks:
    backend:
 
volumes:
    mongo_data:
